server:
  port: 8091

spring:
  #dev 开发环境，test测试环境，pro生产环境
  profiles:
    active: dev
#  thymeleaf:
#    cache: false
#    content-type: text/html
#    mode: LEGACYHTML5
  application:
    name: risk-service #服务名
